### PR TITLE
Fix: Typo

### PR DESCRIPTION
**Pull request by CodeWithEmad**
Hi
noticed there are a couple of 🠆 characters in the readme. replaced them with ->
and also a codejail mention was replaced with xqueue

### CODE REVIEW

**Comment by regisb** [comment]
Arrow characters are properly displayed on my computer:

Screenshot from 2023-08-01 15-08-31

This is a fairly common unicode character and should be available on many platforms. Can you share a screenshot of the square character you are seeing? What's your OS, browser, etc.?

**Comment by CodeWithEmad** [comment]
I'm using Ubuntu 22.04 with Chrome Version 115.0.5790.102
This is what I see: 



And this is my phone:



Maybe it's something only for Mac/Safari??

**Comment by regisb** [comment]
What about this arrow character? →
Source: https://en.wikipedia.org/wiki/Arrows_%28Unicode_block%29

**Comment by CodeWithEmad** [comment]
Yeah, this is fine.
I'll change it to →

**Review by jfavellar90 — APPROVED** [review]

**Review by regisb — APPROVED** [review]
thanks!

**Pull request merged**
